steps:
  # Build a container image which bakes in a source code snapshot and built
  # distribution artifacts.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-container-image'
    args: ['build', '--tag=gcr.io/${PROJECT_ID}/google-spark-connect/google-spark-connect-presubmit:${BUILD_ID}', -f, 'cloudbuild/Dockerfile', '.']
  # Run all unit tests
  - name: 'gcr.io/${PROJECT_ID}/google-spark-connect/google-spark-connect-presubmit:${BUILD_ID}'
    id: 'run-unit-tests'
    waitFor: ['build-container-image']
    entrypoint: 'pytest'
    args: ['-n', 'auto', 'tests/unit']
timeout: 600s
